//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangHocTap {
    
    
    public partial class AdminQuanLyNhom {
        
        /// <summary>
        /// QlTruong control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MangHocTap.ucQLNhom.QlTruong QlTruong;
        
        /// <summary>
        /// QlTruong1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MangHocTap.ucQLNhom.QlTruong QlTruong1;
        
        /// <summary>
        /// QlTruong2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MangHocTap.ucQLNhom.QlTruong QlTruong2;
    }
}
