//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangHocTap.Nhom.NhomChung.KhoaHoc {
    
    
    public partial class Default {
        
        /// <summary>
        /// ucGioiThieu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MangHocTap.Nhom.NhomChung.KhoaHoc.uc.ucGioiThieu ucGioiThieu;
        
        /// <summary>
        /// ucThaoLuan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MangHocTap.Nhom.NhomChung.Truong.uc.ucThaoLuan ucThaoLuan;
    }
}
