#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangHocTap
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="manghoctap_new")]
	public partial class MangHocTapDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBaiVietGhiChu(BaiVietGhiChu instance);
    partial void UpdateBaiVietGhiChu(BaiVietGhiChu instance);
    partial void DeleteBaiVietGhiChu(BaiVietGhiChu instance);
    partial void InsertTruong(Truong instance);
    partial void UpdateTruong(Truong instance);
    partial void DeleteTruong(Truong instance);
    partial void InsertBaiVietMonHoc(BaiVietMonHoc instance);
    partial void UpdateBaiVietMonHoc(BaiVietMonHoc instance);
    partial void DeleteBaiVietMonHoc(BaiVietMonHoc instance);
    partial void InsertBaiVietNhom(BaiVietNhom instance);
    partial void UpdateBaiVietNhom(BaiVietNhom instance);
    partial void DeleteBaiVietNhom(BaiVietNhom instance);
    partial void InsertBanBe(BanBe instance);
    partial void UpdateBanBe(BanBe instance);
    partial void DeleteBanBe(BanBe instance);
    partial void InsertBinhLuanBaiVietNhom(BinhLuanBaiVietNhom instance);
    partial void UpdateBinhLuanBaiVietNhom(BinhLuanBaiVietNhom instance);
    partial void DeleteBinhLuanBaiVietNhom(BinhLuanBaiVietNhom instance);
    partial void InsertBinhLuanBVMH(BinhLuanBVMH instance);
    partial void UpdateBinhLuanBVMH(BinhLuanBVMH instance);
    partial void DeleteBinhLuanBVMH(BinhLuanBVMH instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertMonHoc(MonHoc instance);
    partial void UpdateMonHoc(MonHoc instance);
    partial void DeleteMonHoc(MonHoc instance);
    partial void InsertMonSinh(MonSinh instance);
    partial void UpdateMonSinh(MonSinh instance);
    partial void DeleteMonSinh(MonSinh instance);
    partial void InsertNganh(Nganh instance);
    partial void UpdateNganh(Nganh instance);
    partial void DeleteNganh(Nganh instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    partial void Insertsukiencanhan(sukiencanhan instance);
    partial void Updatesukiencanhan(sukiencanhan instance);
    partial void Deletesukiencanhan(sukiencanhan instance);
    partial void InsertThongBaoBinhLuan(ThongBaoBinhLuan instance);
    partial void UpdateThongBaoBinhLuan(ThongBaoBinhLuan instance);
    partial void DeleteThongBaoBinhLuan(ThongBaoBinhLuan instance);
    partial void InsertTinNhan(TinNhan instance);
    partial void UpdateTinNhan(TinNhan instance);
    partial void DeleteTinNhan(TinNhan instance);
    #endregion
		
		public MangHocTapDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["manghoctap_newConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MangHocTapDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MangHocTapDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MangHocTapDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MangHocTapDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BaiVietGhiChu> BaiVietGhiChus
		{
			get
			{
				return this.GetTable<BaiVietGhiChu>();
			}
		}
		
		public System.Data.Linq.Table<Truong> Truongs
		{
			get
			{
				return this.GetTable<Truong>();
			}
		}
		
		public System.Data.Linq.Table<BaiVietMonHoc> BaiVietMonHocs
		{
			get
			{
				return this.GetTable<BaiVietMonHoc>();
			}
		}
		
		public System.Data.Linq.Table<BaiVietNhom> BaiVietNhoms
		{
			get
			{
				return this.GetTable<BaiVietNhom>();
			}
		}
		
		public System.Data.Linq.Table<BanBe> BanBes
		{
			get
			{
				return this.GetTable<BanBe>();
			}
		}
		
		public System.Data.Linq.Table<BinhLuanBaiVietNhom> BinhLuanBaiVietNhoms
		{
			get
			{
				return this.GetTable<BinhLuanBaiVietNhom>();
			}
		}
		
		public System.Data.Linq.Table<BinhLuanBVMH> BinhLuanBVMHs
		{
			get
			{
				return this.GetTable<BinhLuanBVMH>();
			}
		}
		
		public System.Data.Linq.Table<CapdoCH> CapdoCHes
		{
			get
			{
				return this.GetTable<CapdoCH>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<KinhNghiemHocKy> KinhNghiemHocKies
		{
			get
			{
				return this.GetTable<KinhNghiemHocKy>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<MoiKetBan> MoiKetBans
		{
			get
			{
				return this.GetTable<MoiKetBan>();
			}
		}
		
		public System.Data.Linq.Table<MonHoc> MonHocs
		{
			get
			{
				return this.GetTable<MonHoc>();
			}
		}
		
		public System.Data.Linq.Table<MonSinh> MonSinhs
		{
			get
			{
				return this.GetTable<MonSinh>();
			}
		}
		
		public System.Data.Linq.Table<Nganh> Nganhs
		{
			get
			{
				return this.GetTable<Nganh>();
			}
		}
		
		public System.Data.Linq.Table<NhanThongBao> NhanThongBaos
		{
			get
			{
				return this.GetTable<NhanThongBao>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<sukiencanhan> sukiencanhans
		{
			get
			{
				return this.GetTable<sukiencanhan>();
			}
		}
		
		public System.Data.Linq.Table<ThongBaoBinhLuan> ThongBaoBinhLuans
		{
			get
			{
				return this.GetTable<ThongBaoBinhLuan>();
			}
		}
		
		public System.Data.Linq.Table<TinNhan> TinNhans
		{
			get
			{
				return this.GetTable<TinNhan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaiVietGhiChu")]
	public partial class BaiVietGhiChu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mabaiviet;
		
		private string _tenbaiviet;
		
		private string _noidung;
		
		private System.Nullable<int> _nguoiviet;
		
		private System.Nullable<System.DateTime> _ngayviet;
		
		private string _monhoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabaivietChanging(int value);
    partial void OnmabaivietChanged();
    partial void OntenbaivietChanging(string value);
    partial void OntenbaivietChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnnguoivietChanging(System.Nullable<int> value);
    partial void OnnguoivietChanged();
    partial void OnngayvietChanging(System.Nullable<System.DateTime> value);
    partial void OnngayvietChanged();
    partial void OnmonhocChanging(string value);
    partial void OnmonhocChanged();
    #endregion
		
		public BaiVietGhiChu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabaiviet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mabaiviet
		{
			get
			{
				return this._mabaiviet;
			}
			set
			{
				if ((this._mabaiviet != value))
				{
					this.OnmabaivietChanging(value);
					this.SendPropertyChanging();
					this._mabaiviet = value;
					this.SendPropertyChanged("mabaiviet");
					this.OnmabaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbaiviet", DbType="NVarChar(50)")]
		public string tenbaiviet
		{
			get
			{
				return this._tenbaiviet;
			}
			set
			{
				if ((this._tenbaiviet != value))
				{
					this.OntenbaivietChanging(value);
					this.SendPropertyChanging();
					this._tenbaiviet = value;
					this.SendPropertyChanged("tenbaiviet");
					this.OntenbaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(200)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiviet", DbType="Int")]
		public System.Nullable<int> nguoiviet
		{
			get
			{
				return this._nguoiviet;
			}
			set
			{
				if ((this._nguoiviet != value))
				{
					this.OnnguoivietChanging(value);
					this.SendPropertyChanging();
					this._nguoiviet = value;
					this.SendPropertyChanged("nguoiviet");
					this.OnnguoivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayviet", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayviet
		{
			get
			{
				return this._ngayviet;
			}
			set
			{
				if ((this._ngayviet != value))
				{
					this.OnngayvietChanging(value);
					this.SendPropertyChanging();
					this._ngayviet = value;
					this.SendPropertyChanged("ngayviet");
					this.OnngayvietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monhoc", DbType="VarChar(10)")]
		public string monhoc
		{
			get
			{
				return this._monhoc;
			}
			set
			{
				if ((this._monhoc != value))
				{
					this.OnmonhocChanging(value);
					this.SendPropertyChanging();
					this._monhoc = value;
					this.SendPropertyChanged("monhoc");
					this.OnmonhocChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Truong")]
	public partial class Truong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matruong;
		
		private string _tentruong;
		
		private string _gioithieu;
		
		private string _sodt;
		
		private string _diachi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatruongChanging(string value);
    partial void OnmatruongChanged();
    partial void OntentruongChanging(string value);
    partial void OntentruongChanged();
    partial void OngioithieuChanging(string value);
    partial void OngioithieuChanged();
    partial void OnsodtChanging(string value);
    partial void OnsodtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public Truong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matruong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matruong
		{
			get
			{
				return this._matruong;
			}
			set
			{
				if ((this._matruong != value))
				{
					this.OnmatruongChanging(value);
					this.SendPropertyChanging();
					this._matruong = value;
					this.SendPropertyChanged("matruong");
					this.OnmatruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentruong", DbType="NVarChar(50)")]
		public string tentruong
		{
			get
			{
				return this._tentruong;
			}
			set
			{
				if ((this._tentruong != value))
				{
					this.OntentruongChanging(value);
					this.SendPropertyChanging();
					this._tentruong = value;
					this.SendPropertyChanged("tentruong");
					this.OntentruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(300)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this.OngioithieuChanging(value);
					this.SendPropertyChanging();
					this._gioithieu = value;
					this.SendPropertyChanged("gioithieu");
					this.OngioithieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodt", DbType="NChar(20)")]
		public string sodt
		{
			get
			{
				return this._sodt;
			}
			set
			{
				if ((this._sodt != value))
				{
					this.OnsodtChanging(value);
					this.SendPropertyChanging();
					this._sodt = value;
					this.SendPropertyChanged("sodt");
					this.OnsodtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaiVietMonHoc")]
	public partial class BaiVietMonHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mabaiviet;
		
		private string _tenbaiviet;
		
		private string _noidung;
		
		private System.Nullable<int> _danhgia;
		
		private System.Nullable<int> _nguoiviet;
		
		private System.Nullable<System.DateTime> _ngayviet;
		
		private string _monhoc;
		
		private System.Nullable<int> _loaibai;
		
		private string _tennguoiviet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabaivietChanging(int value);
    partial void OnmabaivietChanged();
    partial void OntenbaivietChanging(string value);
    partial void OntenbaivietChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OndanhgiaChanging(System.Nullable<int> value);
    partial void OndanhgiaChanged();
    partial void OnnguoivietChanging(System.Nullable<int> value);
    partial void OnnguoivietChanged();
    partial void OnngayvietChanging(System.Nullable<System.DateTime> value);
    partial void OnngayvietChanged();
    partial void OnmonhocChanging(string value);
    partial void OnmonhocChanged();
    partial void OnloaibaiChanging(System.Nullable<int> value);
    partial void OnloaibaiChanged();
    partial void OntennguoivietChanging(string value);
    partial void OntennguoivietChanged();
    #endregion
		
		public BaiVietMonHoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabaiviet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mabaiviet
		{
			get
			{
				return this._mabaiviet;
			}
			set
			{
				if ((this._mabaiviet != value))
				{
					this.OnmabaivietChanging(value);
					this.SendPropertyChanging();
					this._mabaiviet = value;
					this.SendPropertyChanged("mabaiviet");
					this.OnmabaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbaiviet", DbType="NVarChar(50)")]
		public string tenbaiviet
		{
			get
			{
				return this._tenbaiviet;
			}
			set
			{
				if ((this._tenbaiviet != value))
				{
					this.OntenbaivietChanging(value);
					this.SendPropertyChanging();
					this._tenbaiviet = value;
					this.SendPropertyChanged("tenbaiviet");
					this.OntenbaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(1000)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danhgia", DbType="Int")]
		public System.Nullable<int> danhgia
		{
			get
			{
				return this._danhgia;
			}
			set
			{
				if ((this._danhgia != value))
				{
					this.OndanhgiaChanging(value);
					this.SendPropertyChanging();
					this._danhgia = value;
					this.SendPropertyChanged("danhgia");
					this.OndanhgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiviet", DbType="Int")]
		public System.Nullable<int> nguoiviet
		{
			get
			{
				return this._nguoiviet;
			}
			set
			{
				if ((this._nguoiviet != value))
				{
					this.OnnguoivietChanging(value);
					this.SendPropertyChanging();
					this._nguoiviet = value;
					this.SendPropertyChanged("nguoiviet");
					this.OnnguoivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayviet", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayviet
		{
			get
			{
				return this._ngayviet;
			}
			set
			{
				if ((this._ngayviet != value))
				{
					this.OnngayvietChanging(value);
					this.SendPropertyChanging();
					this._ngayviet = value;
					this.SendPropertyChanged("ngayviet");
					this.OnngayvietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monhoc", DbType="VarChar(10)")]
		public string monhoc
		{
			get
			{
				return this._monhoc;
			}
			set
			{
				if ((this._monhoc != value))
				{
					this.OnmonhocChanging(value);
					this.SendPropertyChanging();
					this._monhoc = value;
					this.SendPropertyChanged("monhoc");
					this.OnmonhocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaibai", DbType="Int")]
		public System.Nullable<int> loaibai
		{
			get
			{
				return this._loaibai;
			}
			set
			{
				if ((this._loaibai != value))
				{
					this.OnloaibaiChanging(value);
					this.SendPropertyChanging();
					this._loaibai = value;
					this.SendPropertyChanged("loaibai");
					this.OnloaibaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennguoiviet", DbType="NVarChar(50)")]
		public string tennguoiviet
		{
			get
			{
				return this._tennguoiviet;
			}
			set
			{
				if ((this._tennguoiviet != value))
				{
					this.OntennguoivietChanging(value);
					this.SendPropertyChanging();
					this._tennguoiviet = value;
					this.SendPropertyChanged("tennguoiviet");
					this.OntennguoivietChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaiVietNhom")]
	public partial class BaiVietNhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mabaiviet;
		
		private int _ID;
		
		private string _manhom;
		
		private System.DateTime _ngaydang;
		
		private string _noidung;
		
		private System.Nullable<bool> _lathongbao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabaivietChanging(int value);
    partial void OnmabaivietChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnmanhomChanging(string value);
    partial void OnmanhomChanged();
    partial void OnngaydangChanging(System.DateTime value);
    partial void OnngaydangChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnlathongbaoChanging(System.Nullable<bool> value);
    partial void OnlathongbaoChanged();
    #endregion
		
		public BaiVietNhom()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabaiviet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mabaiviet
		{
			get
			{
				return this._mabaiviet;
			}
			set
			{
				if ((this._mabaiviet != value))
				{
					this.OnmabaivietChanging(value);
					this.SendPropertyChanging();
					this._mabaiviet = value;
					this.SendPropertyChanged("mabaiviet");
					this.OnmabaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhom", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string manhom
		{
			get
			{
				return this._manhom;
			}
			set
			{
				if ((this._manhom != value))
				{
					this.OnmanhomChanging(value);
					this.SendPropertyChanging();
					this._manhom = value;
					this.SendPropertyChanged("manhom");
					this.OnmanhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="DateTime NOT NULL")]
		public System.DateTime ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this.OnngaydangChanging(value);
					this.SendPropertyChanging();
					this._ngaydang = value;
					this.SendPropertyChanged("ngaydang");
					this.OnngaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lathongbao", DbType="Bit")]
		public System.Nullable<bool> lathongbao
		{
			get
			{
				return this._lathongbao;
			}
			set
			{
				if ((this._lathongbao != value))
				{
					this.OnlathongbaoChanging(value);
					this.SendPropertyChanging();
					this._lathongbao = value;
					this.SendPropertyChanged("lathongbao");
					this.OnlathongbaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BanBe")]
	public partial class BanBe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id1;
		
		private int _id2;
		
		private System.Nullable<int> _quanhe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid1Changing(int value);
    partial void Onid1Changed();
    partial void Onid2Changing(int value);
    partial void Onid2Changed();
    partial void OnquanheChanging(System.Nullable<int> value);
    partial void OnquanheChanged();
    #endregion
		
		public BanBe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id1", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id1
		{
			get
			{
				return this._id1;
			}
			set
			{
				if ((this._id1 != value))
				{
					this.Onid1Changing(value);
					this.SendPropertyChanging();
					this._id1 = value;
					this.SendPropertyChanged("id1");
					this.Onid1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id2", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id2
		{
			get
			{
				return this._id2;
			}
			set
			{
				if ((this._id2 != value))
				{
					this.Onid2Changing(value);
					this.SendPropertyChanging();
					this._id2 = value;
					this.SendPropertyChanged("id2");
					this.Onid2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quanhe", DbType="Int")]
		public System.Nullable<int> quanhe
		{
			get
			{
				return this._quanhe;
			}
			set
			{
				if ((this._quanhe != value))
				{
					this.OnquanheChanging(value);
					this.SendPropertyChanging();
					this._quanhe = value;
					this.SendPropertyChanged("quanhe");
					this.OnquanheChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BinhLuanBaiVietNhom")]
	public partial class BinhLuanBaiVietNhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mabinhluan;
		
		private int _mabaiviet;
		
		private string _noidung;
		
		private System.DateTime _ngaydang;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabinhluanChanging(int value);
    partial void OnmabinhluanChanged();
    partial void OnmabaivietChanging(int value);
    partial void OnmabaivietChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnngaydangChanging(System.DateTime value);
    partial void OnngaydangChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public BinhLuanBaiVietNhom()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabinhluan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mabinhluan
		{
			get
			{
				return this._mabinhluan;
			}
			set
			{
				if ((this._mabinhluan != value))
				{
					this.OnmabinhluanChanging(value);
					this.SendPropertyChanging();
					this._mabinhluan = value;
					this.SendPropertyChanged("mabinhluan");
					this.OnmabinhluanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabaiviet", DbType="Int NOT NULL")]
		public int mabaiviet
		{
			get
			{
				return this._mabaiviet;
			}
			set
			{
				if ((this._mabaiviet != value))
				{
					this.OnmabaivietChanging(value);
					this.SendPropertyChanging();
					this._mabaiviet = value;
					this.SendPropertyChanged("mabaiviet");
					this.OnmabaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="DateTime NOT NULL")]
		public System.DateTime ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this.OnngaydangChanging(value);
					this.SendPropertyChanging();
					this._ngaydang = value;
					this.SendPropertyChanged("ngaydang");
					this.OnngaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BinhLuanBVMH")]
	public partial class BinhLuanBVMH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mabaiviet;
		
		private string _noidung;
		
		private System.Nullable<int> _danhgia;
		
		private System.Nullable<bool> _haynhat;
		
		private System.Nullable<int> _nguoiviet;
		
		private System.Nullable<System.DateTime> _ngayviet;
		
		private System.Nullable<int> _baivietmonhoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabaivietChanging(int value);
    partial void OnmabaivietChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OndanhgiaChanging(System.Nullable<int> value);
    partial void OndanhgiaChanged();
    partial void OnhaynhatChanging(System.Nullable<bool> value);
    partial void OnhaynhatChanged();
    partial void OnnguoivietChanging(System.Nullable<int> value);
    partial void OnnguoivietChanged();
    partial void OnngayvietChanging(System.Nullable<System.DateTime> value);
    partial void OnngayvietChanged();
    partial void OnbaivietmonhocChanging(System.Nullable<int> value);
    partial void OnbaivietmonhocChanged();
    #endregion
		
		public BinhLuanBVMH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabaiviet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mabaiviet
		{
			get
			{
				return this._mabaiviet;
			}
			set
			{
				if ((this._mabaiviet != value))
				{
					this.OnmabaivietChanging(value);
					this.SendPropertyChanging();
					this._mabaiviet = value;
					this.SendPropertyChanged("mabaiviet");
					this.OnmabaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(1000)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danhgia", DbType="Int")]
		public System.Nullable<int> danhgia
		{
			get
			{
				return this._danhgia;
			}
			set
			{
				if ((this._danhgia != value))
				{
					this.OndanhgiaChanging(value);
					this.SendPropertyChanging();
					this._danhgia = value;
					this.SendPropertyChanged("danhgia");
					this.OndanhgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haynhat", DbType="Bit")]
		public System.Nullable<bool> haynhat
		{
			get
			{
				return this._haynhat;
			}
			set
			{
				if ((this._haynhat != value))
				{
					this.OnhaynhatChanging(value);
					this.SendPropertyChanging();
					this._haynhat = value;
					this.SendPropertyChanged("haynhat");
					this.OnhaynhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoiviet", DbType="Int")]
		public System.Nullable<int> nguoiviet
		{
			get
			{
				return this._nguoiviet;
			}
			set
			{
				if ((this._nguoiviet != value))
				{
					this.OnnguoivietChanging(value);
					this.SendPropertyChanging();
					this._nguoiviet = value;
					this.SendPropertyChanged("nguoiviet");
					this.OnnguoivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayviet", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayviet
		{
			get
			{
				return this._ngayviet;
			}
			set
			{
				if ((this._ngayviet != value))
				{
					this.OnngayvietChanging(value);
					this.SendPropertyChanging();
					this._ngayviet = value;
					this.SendPropertyChanged("ngayviet");
					this.OnngayvietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baivietmonhoc", DbType="Int")]
		public System.Nullable<int> baivietmonhoc
		{
			get
			{
				return this._baivietmonhoc;
			}
			set
			{
				if ((this._baivietmonhoc != value))
				{
					this.OnbaivietmonhocChanging(value);
					this.SendPropertyChanging();
					this._baivietmonhoc = value;
					this.SendPropertyChanged("baivietmonhoc");
					this.OnbaivietmonhocChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapdoCH")]
	public partial class CapdoCH
	{
		
		private System.Nullable<int> _diemch;
		
		private string _tencapdo;
		
		private string _anhcapdo;
		
		private string _maucapdo;
		
		public CapdoCH()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemch", DbType="Int")]
		public System.Nullable<int> diemch
		{
			get
			{
				return this._diemch;
			}
			set
			{
				if ((this._diemch != value))
				{
					this._diemch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tencapdo", DbType="NVarChar(30)")]
		public string tencapdo
		{
			get
			{
				return this._tencapdo;
			}
			set
			{
				if ((this._tencapdo != value))
				{
					this._tencapdo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anhcapdo", DbType="NVarChar(50)")]
		public string anhcapdo
		{
			get
			{
				return this._anhcapdo;
			}
			set
			{
				if ((this._anhcapdo != value))
				{
					this._anhcapdo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maucapdo", DbType="VarChar(20)")]
		public string maucapdo
		{
			get
			{
				return this._maucapdo;
			}
			set
			{
				if ((this._maucapdo != value))
				{
					this._maucapdo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makhoa;
		
		private string _tenkhoa;
		
		private string _matruong;
		
		private string _gioithieu;
		
		private string _sodt;
		
		private string _diachi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhoaChanging(string value);
    partial void OnmakhoaChanged();
    partial void OntenkhoaChanging(string value);
    partial void OntenkhoaChanged();
    partial void OnmatruongChanging(string value);
    partial void OnmatruongChanged();
    partial void OngioithieuChanging(string value);
    partial void OngioithieuChanged();
    partial void OnsodtChanging(string value);
    partial void OnsodtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public Khoa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhoa", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makhoa
		{
			get
			{
				return this._makhoa;
			}
			set
			{
				if ((this._makhoa != value))
				{
					this.OnmakhoaChanging(value);
					this.SendPropertyChanging();
					this._makhoa = value;
					this.SendPropertyChanged("makhoa");
					this.OnmakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhoa", DbType="NVarChar(50)")]
		public string tenkhoa
		{
			get
			{
				return this._tenkhoa;
			}
			set
			{
				if ((this._tenkhoa != value))
				{
					this.OntenkhoaChanging(value);
					this.SendPropertyChanging();
					this._tenkhoa = value;
					this.SendPropertyChanged("tenkhoa");
					this.OntenkhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matruong", DbType="VarChar(10)")]
		public string matruong
		{
			get
			{
				return this._matruong;
			}
			set
			{
				if ((this._matruong != value))
				{
					this.OnmatruongChanging(value);
					this.SendPropertyChanging();
					this._matruong = value;
					this.SendPropertyChanged("matruong");
					this.OnmatruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(300)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this.OngioithieuChanging(value);
					this.SendPropertyChanging();
					this._gioithieu = value;
					this.SendPropertyChanged("gioithieu");
					this.OngioithieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodt", DbType="NChar(20)")]
		public string sodt
		{
			get
			{
				return this._sodt;
			}
			set
			{
				if ((this._sodt != value))
				{
					this.OnsodtChanging(value);
					this.SendPropertyChanging();
					this._sodt = value;
					this.SendPropertyChanged("sodt");
					this.OnsodtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KinhNghiemHocKy")]
	public partial class KinhNghiemHocKy
	{
		
		private System.Nullable<int> _mabaiviet;
		
		private string _noidung;
		
		private System.Nullable<int> _diem;
		
		private string _idviet;
		
		private System.Nullable<System.DateTime> _time;
		
		private System.Nullable<int> _hocky;
		
		private string _nganh;
		
		private string _tennguoiviet;
		
		public KinhNghiemHocKy()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabaiviet", DbType="Int")]
		public System.Nullable<int> mabaiviet
		{
			get
			{
				return this._mabaiviet;
			}
			set
			{
				if ((this._mabaiviet != value))
				{
					this._mabaiviet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(1000)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem", DbType="Int")]
		public System.Nullable<int> diem
		{
			get
			{
				return this._diem;
			}
			set
			{
				if ((this._diem != value))
				{
					this._diem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idviet", DbType="NChar(10)")]
		public string idviet
		{
			get
			{
				return this._idviet;
			}
			set
			{
				if ((this._idviet != value))
				{
					this._idviet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hocky", DbType="Int")]
		public System.Nullable<int> hocky
		{
			get
			{
				return this._hocky;
			}
			set
			{
				if ((this._hocky != value))
				{
					this._hocky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nganh", DbType="VarChar(10)")]
		public string nganh
		{
			get
			{
				return this._nganh;
			}
			set
			{
				if ((this._nganh != value))
				{
					this._nganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennguoiviet", DbType="NVarChar(50)")]
		public string tennguoiviet
		{
			get
			{
				return this._tennguoiviet;
			}
			set
			{
				if ((this._tennguoiviet != value))
				{
					this._tennguoiviet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _malop;
		
		private string _tenlop;
		
		private string _manganh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    partial void OntenlopChanging(string value);
    partial void OntenlopChanged();
    partial void OnmanganhChanging(string value);
    partial void OnmanganhChanged();
    #endregion
		
		public Lop()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlop", DbType="NVarChar(50)")]
		public string tenlop
		{
			get
			{
				return this._tenlop;
			}
			set
			{
				if ((this._tenlop != value))
				{
					this.OntenlopChanging(value);
					this.SendPropertyChanging();
					this._tenlop = value;
					this.SendPropertyChanged("tenlop");
					this.OntenlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manganh", DbType="VarChar(10)")]
		public string manganh
		{
			get
			{
				return this._manganh;
			}
			set
			{
				if ((this._manganh != value))
				{
					this.OnmanganhChanging(value);
					this.SendPropertyChanging();
					this._manganh = value;
					this.SendPropertyChanged("manganh");
					this.OnmanganhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MoiKetBan")]
	public partial class MoiKetBan
	{
		
		private System.Nullable<int> _id1;
		
		private System.Nullable<int> _id2;
		
		public MoiKetBan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id1", DbType="Int")]
		public System.Nullable<int> id1
		{
			get
			{
				return this._id1;
			}
			set
			{
				if ((this._id1 != value))
				{
					this._id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id2", DbType="Int")]
		public System.Nullable<int> id2
		{
			get
			{
				return this._id2;
			}
			set
			{
				if ((this._id2 != value))
				{
					this._id2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHoc")]
	public partial class MonHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mamonhoc;
		
		private string _manganh;
		
		private string _tenmonhoc;
		
		private System.Nullable<int> _stc;
		
		private System.Nullable<int> _heso;
		
		private string _khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmamonhocChanging(string value);
    partial void OnmamonhocChanged();
    partial void OnmanganhChanging(string value);
    partial void OnmanganhChanged();
    partial void OntenmonhocChanging(string value);
    partial void OntenmonhocChanged();
    partial void OnstcChanging(System.Nullable<int> value);
    partial void OnstcChanged();
    partial void OnhesoChanging(System.Nullable<int> value);
    partial void OnhesoChanged();
    partial void OnkhoaChanging(string value);
    partial void OnkhoaChanged();
    #endregion
		
		public MonHoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamonhoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mamonhoc
		{
			get
			{
				return this._mamonhoc;
			}
			set
			{
				if ((this._mamonhoc != value))
				{
					this.OnmamonhocChanging(value);
					this.SendPropertyChanging();
					this._mamonhoc = value;
					this.SendPropertyChanged("mamonhoc");
					this.OnmamonhocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manganh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manganh
		{
			get
			{
				return this._manganh;
			}
			set
			{
				if ((this._manganh != value))
				{
					this.OnmanganhChanging(value);
					this.SendPropertyChanging();
					this._manganh = value;
					this.SendPropertyChanged("manganh");
					this.OnmanganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenmonhoc", DbType="NVarChar(100)")]
		public string tenmonhoc
		{
			get
			{
				return this._tenmonhoc;
			}
			set
			{
				if ((this._tenmonhoc != value))
				{
					this.OntenmonhocChanging(value);
					this.SendPropertyChanging();
					this._tenmonhoc = value;
					this.SendPropertyChanged("tenmonhoc");
					this.OntenmonhocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stc", DbType="Int")]
		public System.Nullable<int> stc
		{
			get
			{
				return this._stc;
			}
			set
			{
				if ((this._stc != value))
				{
					this.OnstcChanging(value);
					this.SendPropertyChanging();
					this._stc = value;
					this.SendPropertyChanged("stc");
					this.OnstcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heso", DbType="Int")]
		public System.Nullable<int> heso
		{
			get
			{
				return this._heso;
			}
			set
			{
				if ((this._heso != value))
				{
					this.OnhesoChanging(value);
					this.SendPropertyChanging();
					this._heso = value;
					this.SendPropertyChanged("heso");
					this.OnhesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoa", DbType="VarChar(10)")]
		public string khoa
		{
			get
			{
				return this._khoa;
			}
			set
			{
				if ((this._khoa != value))
				{
					this.OnkhoaChanging(value);
					this.SendPropertyChanging();
					this._khoa = value;
					this.SendPropertyChanged("khoa");
					this.OnkhoaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonSinh")]
	public partial class MonSinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mamonhoc;
		
		private int _id;
		
		private System.Nullable<int> _stc;
		
		private System.Nullable<int> _heso;
		
		private System.DateTime _batdau;
		
		private System.DateTime _ketthuc;
		
		private string _thoikhoabieu;
		
		private System.Nullable<double> _diemquatrinh;
		
		private System.Nullable<double> _diemthi;
		
		private System.Nullable<int> _trangthai;
		
		private System.Nullable<int> _hocky;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmamonhocChanging(string value);
    partial void OnmamonhocChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstcChanging(System.Nullable<int> value);
    partial void OnstcChanged();
    partial void OnhesoChanging(System.Nullable<int> value);
    partial void OnhesoChanged();
    partial void OnbatdauChanging(System.DateTime value);
    partial void OnbatdauChanged();
    partial void OnketthucChanging(System.DateTime value);
    partial void OnketthucChanged();
    partial void OnthoikhoabieuChanging(string value);
    partial void OnthoikhoabieuChanged();
    partial void OndiemquatrinhChanging(System.Nullable<double> value);
    partial void OndiemquatrinhChanged();
    partial void OndiemthiChanging(System.Nullable<double> value);
    partial void OndiemthiChanged();
    partial void OntrangthaiChanging(System.Nullable<int> value);
    partial void OntrangthaiChanged();
    partial void OnhockyChanging(System.Nullable<int> value);
    partial void OnhockyChanged();
    #endregion
		
		public MonSinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamonhoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mamonhoc
		{
			get
			{
				return this._mamonhoc;
			}
			set
			{
				if ((this._mamonhoc != value))
				{
					this.OnmamonhocChanging(value);
					this.SendPropertyChanging();
					this._mamonhoc = value;
					this.SendPropertyChanged("mamonhoc");
					this.OnmamonhocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stc", DbType="Int")]
		public System.Nullable<int> stc
		{
			get
			{
				return this._stc;
			}
			set
			{
				if ((this._stc != value))
				{
					this.OnstcChanging(value);
					this.SendPropertyChanging();
					this._stc = value;
					this.SendPropertyChanged("stc");
					this.OnstcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heso", DbType="Int")]
		public System.Nullable<int> heso
		{
			get
			{
				return this._heso;
			}
			set
			{
				if ((this._heso != value))
				{
					this.OnhesoChanging(value);
					this.SendPropertyChanging();
					this._heso = value;
					this.SendPropertyChanged("heso");
					this.OnhesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_batdau", DbType="Date NOT NULL")]
		public System.DateTime batdau
		{
			get
			{
				return this._batdau;
			}
			set
			{
				if ((this._batdau != value))
				{
					this.OnbatdauChanging(value);
					this.SendPropertyChanging();
					this._batdau = value;
					this.SendPropertyChanged("batdau");
					this.OnbatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketthuc", DbType="Date NOT NULL")]
		public System.DateTime ketthuc
		{
			get
			{
				return this._ketthuc;
			}
			set
			{
				if ((this._ketthuc != value))
				{
					this.OnketthucChanging(value);
					this.SendPropertyChanging();
					this._ketthuc = value;
					this.SendPropertyChanged("ketthuc");
					this.OnketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoikhoabieu", DbType="NVarChar(100)")]
		public string thoikhoabieu
		{
			get
			{
				return this._thoikhoabieu;
			}
			set
			{
				if ((this._thoikhoabieu != value))
				{
					this.OnthoikhoabieuChanging(value);
					this.SendPropertyChanging();
					this._thoikhoabieu = value;
					this.SendPropertyChanged("thoikhoabieu");
					this.OnthoikhoabieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemquatrinh", DbType="Float")]
		public System.Nullable<double> diemquatrinh
		{
			get
			{
				return this._diemquatrinh;
			}
			set
			{
				if ((this._diemquatrinh != value))
				{
					this.OndiemquatrinhChanging(value);
					this.SendPropertyChanging();
					this._diemquatrinh = value;
					this.SendPropertyChanged("diemquatrinh");
					this.OndiemquatrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemthi", DbType="Float")]
		public System.Nullable<double> diemthi
		{
			get
			{
				return this._diemthi;
			}
			set
			{
				if ((this._diemthi != value))
				{
					this.OndiemthiChanging(value);
					this.SendPropertyChanging();
					this._diemthi = value;
					this.SendPropertyChanged("diemthi");
					this.OndiemthiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Int")]
		public System.Nullable<int> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hocky", DbType="Int")]
		public System.Nullable<int> hocky
		{
			get
			{
				return this._hocky;
			}
			set
			{
				if ((this._hocky != value))
				{
					this.OnhockyChanging(value);
					this.SendPropertyChanging();
					this._hocky = value;
					this.SendPropertyChanged("hocky");
					this.OnhockyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nganh")]
	public partial class Nganh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manganh;
		
		private string _tennganh;
		
		private string _gioithieu;
		
		private string _makhoa;
		
		private System.Nullable<int> _sonamdaotao;
		
		private System.Nullable<int> _khoabd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanganhChanging(string value);
    partial void OnmanganhChanged();
    partial void OntennganhChanging(string value);
    partial void OntennganhChanged();
    partial void OngioithieuChanging(string value);
    partial void OngioithieuChanged();
    partial void OnmakhoaChanging(string value);
    partial void OnmakhoaChanged();
    partial void OnsonamdaotaoChanging(System.Nullable<int> value);
    partial void OnsonamdaotaoChanged();
    partial void OnkhoabdChanging(System.Nullable<int> value);
    partial void OnkhoabdChanged();
    #endregion
		
		public Nganh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manganh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manganh
		{
			get
			{
				return this._manganh;
			}
			set
			{
				if ((this._manganh != value))
				{
					this.OnmanganhChanging(value);
					this.SendPropertyChanging();
					this._manganh = value;
					this.SendPropertyChanged("manganh");
					this.OnmanganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennganh", DbType="NVarChar(50)")]
		public string tennganh
		{
			get
			{
				return this._tennganh;
			}
			set
			{
				if ((this._tennganh != value))
				{
					this.OntennganhChanging(value);
					this.SendPropertyChanging();
					this._tennganh = value;
					this.SendPropertyChanged("tennganh");
					this.OntennganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(300)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this.OngioithieuChanging(value);
					this.SendPropertyChanging();
					this._gioithieu = value;
					this.SendPropertyChanged("gioithieu");
					this.OngioithieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhoa", DbType="VarChar(10)")]
		public string makhoa
		{
			get
			{
				return this._makhoa;
			}
			set
			{
				if ((this._makhoa != value))
				{
					this.OnmakhoaChanging(value);
					this.SendPropertyChanging();
					this._makhoa = value;
					this.SendPropertyChanged("makhoa");
					this.OnmakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonamdaotao", DbType="Int")]
		public System.Nullable<int> sonamdaotao
		{
			get
			{
				return this._sonamdaotao;
			}
			set
			{
				if ((this._sonamdaotao != value))
				{
					this.OnsonamdaotaoChanging(value);
					this.SendPropertyChanging();
					this._sonamdaotao = value;
					this.SendPropertyChanged("sonamdaotao");
					this.OnsonamdaotaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoabd", DbType="Int")]
		public System.Nullable<int> khoabd
		{
			get
			{
				return this._khoabd;
			}
			set
			{
				if ((this._khoabd != value))
				{
					this.OnkhoabdChanging(value);
					this.SendPropertyChanging();
					this._khoabd = value;
					this.SendPropertyChanged("khoabd");
					this.OnkhoabdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanThongBao")]
	public partial class NhanThongBao
	{
		
		private System.Nullable<int> _mathongbao;
		
		private string _nguoinhan;
		
		public NhanThongBao()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mathongbao", DbType="Int")]
		public System.Nullable<int> mathongbao
		{
			get
			{
				return this._mathongbao;
			}
			set
			{
				if ((this._mathongbao != value))
				{
					this._mathongbao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoinhan", DbType="VarChar(8000)")]
		public string nguoinhan
		{
			get
			{
				return this._nguoinhan;
			}
			set
			{
				if ((this._nguoinhan != value))
				{
					this._nguoinhan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _matkhau;
		
		private string _hoten;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _sodt;
		
		private System.Nullable<bool> _gioitinh;
		
		private System.Nullable<int> _trangthai;
		
		private string _avatar;
		
		private System.Nullable<int> _diemconghien;
		
		private string _nienkhoa;
		
		private string _matruong;
		
		private string _makhoa;
		
		private string _manganh;
		
		private string _malop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OnsodtChanging(string value);
    partial void OnsodtChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OntrangthaiChanging(System.Nullable<int> value);
    partial void OntrangthaiChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void OndiemconghienChanging(System.Nullable<int> value);
    partial void OndiemconghienChanged();
    partial void OnnienkhoaChanging(string value);
    partial void OnnienkhoaChanged();
    partial void OnmatruongChanging(string value);
    partial void OnmatruongChanged();
    partial void OnmakhoaChanging(string value);
    partial void OnmakhoaChanged();
    partial void OnmanganhChanging(string value);
    partial void OnmanganhChanged();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    #endregion
		
		public SinhVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodt", DbType="NChar(20)")]
		public string sodt
		{
			get
			{
				return this._sodt;
			}
			set
			{
				if ((this._sodt != value))
				{
					this.OnsodtChanging(value);
					this.SendPropertyChanging();
					this._sodt = value;
					this.SendPropertyChanged("sodt");
					this.OnsodtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Int")]
		public System.Nullable<int> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(50)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemconghien", DbType="Int")]
		public System.Nullable<int> diemconghien
		{
			get
			{
				return this._diemconghien;
			}
			set
			{
				if ((this._diemconghien != value))
				{
					this.OndiemconghienChanging(value);
					this.SendPropertyChanging();
					this._diemconghien = value;
					this.SendPropertyChanged("diemconghien");
					this.OndiemconghienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nienkhoa", DbType="VarChar(10)")]
		public string nienkhoa
		{
			get
			{
				return this._nienkhoa;
			}
			set
			{
				if ((this._nienkhoa != value))
				{
					this.OnnienkhoaChanging(value);
					this.SendPropertyChanging();
					this._nienkhoa = value;
					this.SendPropertyChanged("nienkhoa");
					this.OnnienkhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matruong", DbType="VarChar(10)")]
		public string matruong
		{
			get
			{
				return this._matruong;
			}
			set
			{
				if ((this._matruong != value))
				{
					this.OnmatruongChanging(value);
					this.SendPropertyChanging();
					this._matruong = value;
					this.SendPropertyChanged("matruong");
					this.OnmatruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhoa", DbType="VarChar(10)")]
		public string makhoa
		{
			get
			{
				return this._makhoa;
			}
			set
			{
				if ((this._makhoa != value))
				{
					this.OnmakhoaChanging(value);
					this.SendPropertyChanging();
					this._makhoa = value;
					this.SendPropertyChanged("makhoa");
					this.OnmakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manganh", DbType="VarChar(10)")]
		public string manganh
		{
			get
			{
				return this._manganh;
			}
			set
			{
				if ((this._manganh != value))
				{
					this.OnmanganhChanging(value);
					this.SendPropertyChanging();
					this._manganh = value;
					this.SendPropertyChanged("manganh");
					this.OnmanganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="VarChar(10)")]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sukiencanhan")]
	public partial class sukiencanhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _tensukien;
		
		private string _noidung;
		
		private System.DateTime _batdau;
		
		private System.DateTime _ketthuc;
		
		private string _nguoithamgia;
		
		private string _diadiem;
		
		private int _SV_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntensukienChanging(string value);
    partial void OntensukienChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnbatdauChanging(System.DateTime value);
    partial void OnbatdauChanged();
    partial void OnketthucChanging(System.DateTime value);
    partial void OnketthucChanged();
    partial void OnnguoithamgiaChanging(string value);
    partial void OnnguoithamgiaChanged();
    partial void OndiadiemChanging(string value);
    partial void OndiadiemChanged();
    partial void OnSV_IDChanging(int value);
    partial void OnSV_IDChanged();
    #endregion
		
		public sukiencanhan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensukien", DbType="NVarChar(50)")]
		public string tensukien
		{
			get
			{
				return this._tensukien;
			}
			set
			{
				if ((this._tensukien != value))
				{
					this.OntensukienChanging(value);
					this.SendPropertyChanging();
					this._tensukien = value;
					this.SendPropertyChanged("tensukien");
					this.OntensukienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(200)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_batdau", DbType="DateTime NOT NULL")]
		public System.DateTime batdau
		{
			get
			{
				return this._batdau;
			}
			set
			{
				if ((this._batdau != value))
				{
					this.OnbatdauChanging(value);
					this.SendPropertyChanging();
					this._batdau = value;
					this.SendPropertyChanged("batdau");
					this.OnbatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketthuc", DbType="DateTime NOT NULL")]
		public System.DateTime ketthuc
		{
			get
			{
				return this._ketthuc;
			}
			set
			{
				if ((this._ketthuc != value))
				{
					this.OnketthucChanging(value);
					this.SendPropertyChanging();
					this._ketthuc = value;
					this.SendPropertyChanged("ketthuc");
					this.OnketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoithamgia", DbType="NVarChar(MAX)")]
		public string nguoithamgia
		{
			get
			{
				return this._nguoithamgia;
			}
			set
			{
				if ((this._nguoithamgia != value))
				{
					this.OnnguoithamgiaChanging(value);
					this.SendPropertyChanging();
					this._nguoithamgia = value;
					this.SendPropertyChanged("nguoithamgia");
					this.OnnguoithamgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diadiem", DbType="NVarChar(50)")]
		public string diadiem
		{
			get
			{
				return this._diadiem;
			}
			set
			{
				if ((this._diadiem != value))
				{
					this.OndiadiemChanging(value);
					this.SendPropertyChanging();
					this._diadiem = value;
					this.SendPropertyChanged("diadiem");
					this.OndiadiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV_ID", DbType="Int NOT NULL")]
		public int SV_ID
		{
			get
			{
				return this._SV_ID;
			}
			set
			{
				if ((this._SV_ID != value))
				{
					this.OnSV_IDChanging(value);
					this.SendPropertyChanging();
					this._SV_ID = value;
					this.SendPropertyChanged("SV_ID");
					this.OnSV_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongBaoBinhLuan")]
	public partial class ThongBaoBinhLuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _mabaiviet;
		
		private int _loai;
		
		private string _NoiDung;
		
		private string _Link;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnmabaivietChanging(int value);
    partial void OnmabaivietChanged();
    partial void OnloaiChanging(int value);
    partial void OnloaiChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public ThongBaoBinhLuan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabaiviet", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mabaiviet
		{
			get
			{
				return this._mabaiviet;
			}
			set
			{
				if ((this._mabaiviet != value))
				{
					this.OnmabaivietChanging(value);
					this.SendPropertyChanging();
					this._mabaiviet = value;
					this.SendPropertyChanged("mabaiviet");
					this.OnmabaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int loai
		{
			get
			{
				return this._loai;
			}
			set
			{
				if ((this._loai != value))
				{
					this.OnloaiChanging(value);
					this.SendPropertyChanging();
					this._loai = value;
					this.SendPropertyChanged("loai");
					this.OnloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(200)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(100)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinNhan")]
	public partial class TinNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _matinnhan;
		
		private int _nguoinhan;
		
		private int _nguoigui;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaynhan;
		
		private System.Nullable<int> _trangthai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatinnhanChanging(int value);
    partial void OnmatinnhanChanged();
    partial void OnnguoinhanChanging(int value);
    partial void OnnguoinhanChanged();
    partial void OnnguoiguiChanging(int value);
    partial void OnnguoiguiChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnngaynhanChanging(System.Nullable<System.DateTime> value);
    partial void OnngaynhanChanged();
    partial void OntrangthaiChanging(System.Nullable<int> value);
    partial void OntrangthaiChanged();
    #endregion
		
		public TinNhan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matinnhan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int matinnhan
		{
			get
			{
				return this._matinnhan;
			}
			set
			{
				if ((this._matinnhan != value))
				{
					this.OnmatinnhanChanging(value);
					this.SendPropertyChanging();
					this._matinnhan = value;
					this.SendPropertyChanged("matinnhan");
					this.OnmatinnhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoinhan", DbType="Int NOT NULL")]
		public int nguoinhan
		{
			get
			{
				return this._nguoinhan;
			}
			set
			{
				if ((this._nguoinhan != value))
				{
					this.OnnguoinhanChanging(value);
					this.SendPropertyChanging();
					this._nguoinhan = value;
					this.SendPropertyChanged("nguoinhan");
					this.OnnguoinhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoigui", DbType="Int NOT NULL")]
		public int nguoigui
		{
			get
			{
				return this._nguoigui;
			}
			set
			{
				if ((this._nguoigui != value))
				{
					this.OnnguoiguiChanging(value);
					this.SendPropertyChanging();
					this._nguoigui = value;
					this.SendPropertyChanged("nguoigui");
					this.OnnguoiguiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(500)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaynhan
		{
			get
			{
				return this._ngaynhan;
			}
			set
			{
				if ((this._ngaynhan != value))
				{
					this.OnngaynhanChanging(value);
					this.SendPropertyChanging();
					this._ngaynhan = value;
					this.SendPropertyChanged("ngaynhan");
					this.OnngaynhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Int")]
		public System.Nullable<int> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
